-- ECLADO procurement purchase orders, line-item snapshots and reusable addresses.
-- Run after supabase-procurement-catalog.sql and supabase-admin-users.sql.

create sequence if not exists public.purchase_order_number_seq;

create or replace function public.next_purchase_order_number()
returns text
language sql
volatile
security definer
set search_path = ''
as $$
  select 'PO-' || to_char(now() at time zone 'Asia/Taipei', 'YYYYMMDD') || '-'
    || lpad(nextval('public.purchase_order_number_seq')::text, 4, '0');
$$;

revoke all on function public.next_purchase_order_number() from public, anon, authenticated;

create table if not exists public.procurement_addresses (
  id bigint generated by default as identity primary key,
  address_text text not null,
  is_default boolean not null default false,
  active boolean not null default true,
  usage_count integer not null default 0 check (usage_count >= 0),
  last_used_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint procurement_addresses_address_not_blank check (btrim(address_text) <> '')
);

-- Remove the earlier split-address design when this migration is rerun.
alter table public.procurement_addresses
  drop column if exists label,
  drop column if exists recipient_name,
  drop column if exists country,
  drop column if exists postal_code,
  drop column if exists phone;

create unique index if not exists procurement_addresses_one_default
  on public.procurement_addresses (is_default)
  where is_default is true and active is true;

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  po_number text not null default public.next_purchase_order_number(),
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  status text not null default 'draft',
  currency text not null default 'USD',
  exchange_rate numeric(14, 6) not null,
  total_usd numeric(14, 2) not null default 0,
  total_twd numeric(14, 2) not null default 0,
  shipping_address jsonb not null default '{}'::jsonb,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ordered_at timestamptz,
  received_at timestamptz,
  constraint purchase_orders_po_number_unique unique (po_number),
  constraint purchase_orders_status_valid check (
    status in ('draft', 'pending', 'ordered', 'shipping', 'received', 'cancelled')
  ),
  constraint purchase_orders_currency_usd check (currency = 'USD'),
  constraint purchase_orders_exchange_rate_positive check (exchange_rate > 0),
  constraint purchase_orders_totals_nonnegative check (total_usd >= 0 and total_twd >= 0)
);

create index if not exists purchase_orders_created_idx
  on public.purchase_orders (created_at desc, id desc);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  supplier_item_id bigint not null references public.supplier_items(id) on delete restrict,
  supplier_price_id bigint references public.supplier_item_prices(id) on delete set null,
  supplier_sku text not null,
  name_zh text,
  name_en text not null,
  specification text,
  quantity integer not null,
  currency text not null default 'USD',
  unit_cost numeric(14, 4) not null,
  subtotal_usd numeric(14, 2) not null,
  stock_at_order integer,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint purchase_order_items_quantity_positive check (quantity > 0),
  constraint purchase_order_items_currency_usd check (currency = 'USD'),
  constraint purchase_order_items_cost_nonnegative check (unit_cost >= 0 and subtotal_usd >= 0),
  constraint purchase_order_items_unique_item unique (purchase_order_id, supplier_item_id)
);

create index if not exists purchase_order_items_order_idx
  on public.purchase_order_items (purchase_order_id, sort_order, id);

drop trigger if exists trg_procurement_addresses_updated_at on public.procurement_addresses;
create trigger trg_procurement_addresses_updated_at
  before update on public.procurement_addresses
  for each row execute function public.set_updated_at();

drop trigger if exists trg_purchase_orders_updated_at on public.purchase_orders;
create trigger trg_purchase_orders_updated_at
  before update on public.purchase_orders
  for each row execute function public.set_updated_at();

alter table public.procurement_addresses enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

revoke all on table public.procurement_addresses from anon, authenticated;
revoke all on table public.purchase_orders from anon, authenticated;
revoke all on table public.purchase_order_items from anon, authenticated;

create or replace function public.get_procurement_management_data()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  payload jsonb;
begin
  if not public.is_eclado_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'suppliers', coalesce((
      select jsonb_agg(to_jsonb(supplier) order by supplier.name)
      from public.suppliers supplier where supplier.active is true
    ), '[]'::jsonb),
    'supplier_items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', item.id,
        'supplier_id', item.supplier_id,
        'supplier_sku', item.supplier_sku,
        'name_en', item.name_en,
        'name_zh', item.name_zh,
        'specification', item.specification,
        'active', item.active,
        'price_id', current_price.id,
        'currency', coalesce(current_price.currency, supplier.default_currency),
        'unit_cost', current_price.unit_cost,
        'has_inventory_link', coalesce(stock.has_inventory_link, false),
        'available_stock', stock.available_stock
      ) order by item.supplier_sku)
      from public.supplier_items item
      join public.suppliers supplier on supplier.id = item.supplier_id
      left join lateral (
        select price.id, price.currency, price.unit_cost
        from public.supplier_item_prices price
        where price.supplier_item_id = item.id
          and price.effective_from <= now()
          and (price.effective_to is null or price.effective_to > now())
        order by price.effective_from desc, price.id desc
        limit 1
      ) current_price on true
      left join lateral (
        select
          count(*) > 0 as has_inventory_link,
          floor(sum(variant.stock / link.conversion_quantity))::integer as available_stock
        from public.supplier_item_variant_links link
        join public.product_variants variant on variant.id = link.product_variant_id
        where link.supplier_item_id = item.id
          and variant.active is true
      ) stock on true
      where item.active is true
    ), '[]'::jsonb),
    'addresses', coalesce((
      select jsonb_agg(to_jsonb(address) order by address.is_default desc, address.last_used_at desc nulls last, address.id desc)
      from public.procurement_addresses address where address.active is true
    ), '[]'::jsonb),
    'orders', coalesce((
      select jsonb_agg(
        to_jsonb(purchase_order) || jsonb_build_object(
          'supplier_name', supplier.name,
          'supplier_code', supplier.code,
          'items', coalesce((
            select jsonb_agg(to_jsonb(order_item) order by order_item.sort_order, order_item.id)
            from public.purchase_order_items order_item
            where order_item.purchase_order_id = purchase_order.id
          ), '[]'::jsonb)
        ) order by purchase_order.created_at desc, purchase_order.id desc
      )
      from public.purchase_orders purchase_order
      join public.suppliers supplier on supplier.id = purchase_order.supplier_id
    ), '[]'::jsonb)
  ) into payload;
  return payload;
end;
$$;

revoke all on function public.get_procurement_management_data() from public, anon;
grant execute on function public.get_procurement_management_data() to authenticated;

create or replace function public.save_procurement_address(p_address jsonb)
returns public.procurement_addresses
language plpgsql
security definer
set search_path = ''
as $$
declare
  address_id bigint := nullif(p_address ->> 'id', '')::bigint;
  saved public.procurement_addresses%rowtype;
  make_default boolean := coalesce((p_address ->> 'is_default')::boolean, false);
begin
  if not public.is_eclado_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if btrim(coalesce(p_address ->> 'address_text', '')) = '' then
    raise exception 'Shipping address is required' using errcode = '22023';
  end if;
  if make_default then
    update public.procurement_addresses set is_default = false where is_default is true;
  end if;

  if address_id is null then
    insert into public.procurement_addresses (
      address_text, is_default, active, created_by
    ) values (
      btrim(p_address ->> 'address_text'), make_default, true, auth.uid()
    ) returning * into saved;
  else
    update public.procurement_addresses set
      address_text = btrim(p_address ->> 'address_text'),
      is_default = make_default,
      active = true
    where id = address_id
    returning * into saved;
    if saved.id is null then raise exception 'Address not found' using errcode = 'P0002'; end if;
  end if;
  return saved;
end;
$$;

revoke all on function public.save_procurement_address(jsonb) from public, anon;
grant execute on function public.save_procurement_address(jsonb) to authenticated;

create or replace function public.archive_procurement_address(p_address_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_eclado_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  update public.procurement_addresses set active = false, is_default = false where id = p_address_id;
end;
$$;

revoke all on function public.archive_procurement_address(bigint) from public, anon;
grant execute on function public.archive_procurement_address(bigint) to authenticated;

create or replace function public.save_purchase_order(p_order jsonb, p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  order_id bigint := nullif(p_order ->> 'id', '')::bigint;
  supplier_id_value bigint := nullif(p_order ->> 'supplier_id', '')::bigint;
  exchange_rate_value numeric := nullif(p_order ->> 'exchange_rate', '')::numeric;
  status_value text := coalesce(nullif(btrim(p_order ->> 'status'), ''), 'draft');
  address_value jsonb := coalesce(p_order -> 'shipping_address', '{}'::jsonb);
  total_usd_value numeric(14, 2) := 0;
  total_twd_value numeric(14, 2) := 0;
  saved_order public.purchase_orders%rowtype;
  item_value jsonb;
  item_row public.supplier_items%rowtype;
  quantity_value integer;
  unit_cost_value numeric;
  stock_value integer;
  price_id_value bigint;
  item_index integer := 0;
begin
  if not public.is_eclado_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if supplier_id_value is null or not exists (
    select 1 from public.suppliers where id = supplier_id_value and active is true
  ) then raise exception 'Active supplier is required' using errcode = '22023'; end if;
  if exchange_rate_value is null or exchange_rate_value <= 0 then
    raise exception 'Exchange rate must be greater than zero' using errcode = '22023';
  end if;
  if status_value not in ('draft', 'pending') then
    raise exception 'New or edited order status must be draft or pending' using errcode = '22023';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'At least one purchase item is required' using errcode = '22023';
  end if;
  if status_value <> 'draft' and btrim(coalesce(address_value ->> 'address_text', '')) = '' then
    raise exception 'Shipping address is required' using errcode = '22023';
  end if;

  for item_value in select value from jsonb_array_elements(p_items)
  loop
    quantity_value := nullif(item_value ->> 'quantity', '')::integer;
    unit_cost_value := nullif(item_value ->> 'unit_cost', '')::numeric;
    if quantity_value is null or quantity_value <= 0 or unit_cost_value is null or unit_cost_value < 0 then
      raise exception 'Item quantity and unit cost are invalid' using errcode = '22023';
    end if;
    total_usd_value := total_usd_value + round(quantity_value * unit_cost_value, 2);
  end loop;
  total_twd_value := round(total_usd_value * exchange_rate_value, 2);

  if order_id is null then
    insert into public.purchase_orders (
      supplier_id, status, exchange_rate, total_usd, total_twd,
      shipping_address, notes, created_by
    ) values (
      supplier_id_value, status_value, exchange_rate_value, total_usd_value, total_twd_value,
      address_value, nullif(btrim(p_order ->> 'notes'), ''), auth.uid()
    ) returning * into saved_order;
    order_id := saved_order.id;
  else
    update public.purchase_orders set
      supplier_id = supplier_id_value,
      status = status_value,
      exchange_rate = exchange_rate_value,
      total_usd = total_usd_value,
      total_twd = total_twd_value,
      shipping_address = address_value,
      notes = nullif(btrim(p_order ->> 'notes'), '')
    where id = order_id and status in ('draft', 'pending')
    returning * into saved_order;
    if saved_order.id is null then
      raise exception 'Editable purchase order not found' using errcode = 'P0002';
    end if;
    delete from public.purchase_order_items where purchase_order_id = order_id;
  end if;

  for item_value in select value from jsonb_array_elements(p_items)
  loop
    select * into item_row from public.supplier_items
    where id = (item_value ->> 'supplier_item_id')::bigint
      and supplier_id = supplier_id_value and active is true;
    if item_row.id is null then raise exception 'Supplier item not found' using errcode = 'P0002'; end if;
    quantity_value := (item_value ->> 'quantity')::integer;
    unit_cost_value := (item_value ->> 'unit_cost')::numeric;
    price_id_value := nullif(item_value ->> 'supplier_price_id', '')::bigint;
    if price_id_value is not null and not exists (
      select 1 from public.supplier_item_prices price
      where price.id = price_id_value and price.supplier_item_id = item_row.id
    ) then
      price_id_value := null;
    end if;
    select case when count(*) > 0
      then floor(sum(variant.stock / link.conversion_quantity))::integer
      else null end
    into stock_value
    from public.supplier_item_variant_links link
    join public.product_variants variant on variant.id = link.product_variant_id
    where link.supplier_item_id = item_row.id and variant.active is true;

    insert into public.purchase_order_items (
      purchase_order_id, supplier_item_id, supplier_price_id,
      supplier_sku, name_zh, name_en, specification,
      quantity, unit_cost, subtotal_usd, stock_at_order, sort_order
    ) values (
      order_id, item_row.id, price_id_value,
      item_row.supplier_sku, item_row.name_zh, item_row.name_en, item_row.specification,
      quantity_value, unit_cost_value, round(quantity_value * unit_cost_value, 2),
      stock_value, item_index
    );
    item_index := item_index + 1;
  end loop;

  if nullif(p_order ->> 'address_id', '') is not null then
    update public.procurement_addresses set
      usage_count = usage_count + 1,
      last_used_at = now()
    where id = (p_order ->> 'address_id')::bigint and active is true;
  end if;

  return jsonb_build_object(
    'id', saved_order.id,
    'po_number', saved_order.po_number,
    'status', saved_order.status,
    'total_usd', saved_order.total_usd,
    'total_twd', saved_order.total_twd
  );
end;
$$;

revoke all on function public.save_purchase_order(jsonb, jsonb) from public, anon;
grant execute on function public.save_purchase_order(jsonb, jsonb) to authenticated;

create or replace function public.update_purchase_order_status(p_order_id bigint, p_status text)
returns public.purchase_orders
language plpgsql
security definer
set search_path = ''
as $$
declare saved public.purchase_orders%rowtype;
begin
  if not public.is_eclado_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if p_status not in ('draft', 'pending', 'ordered', 'shipping', 'received') then
    raise exception 'Invalid purchase order status' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.purchase_orders
    where id = p_order_id
      and status in ('ordered', 'shipping', 'received')
      and p_status in ('draft', 'pending')
  ) then
    raise exception 'Processed purchase orders cannot return to draft or pending' using errcode = '22023';
  end if;
  update public.purchase_orders set
    status = p_status,
    ordered_at = case when p_status = 'ordered' and ordered_at is null then now() else ordered_at end,
    received_at = case when p_status = 'received' and received_at is null then now() else received_at end
  where id = p_order_id
  returning * into saved;
  if saved.id is null then raise exception 'Purchase order not found' using errcode = 'P0002'; end if;
  return saved;
end;
$$;

revoke all on function public.update_purchase_order_status(bigint, text) from public, anon;
grant execute on function public.update_purchase_order_status(bigint, text) to authenticated;

create or replace function public.delete_purchase_order(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_id bigint;
begin
  if not public.is_eclado_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  delete from public.purchase_orders
  where id = p_order_id
    and status in ('draft', 'pending')
  returning id into deleted_id;

  if deleted_id is null then
    if exists (select 1 from public.purchase_orders where id = p_order_id) then
      raise exception 'Only draft or pending purchase orders can be deleted' using errcode = '22023';
    end if;
    raise exception 'Purchase order not found' using errcode = 'P0002';
  end if;
end;
$$;

revoke all on function public.delete_purchase_order(bigint) from public, anon;
grant execute on function public.delete_purchase_order(bigint) to authenticated;

comment on table public.purchase_orders is 'Procurement purchase-order headers with exchange-rate and address snapshots.';
comment on table public.purchase_order_items is 'Immutable-at-save product, price and inventory snapshots for each purchase order.';
comment on table public.procurement_addresses is 'Reusable procurement shipping addresses; purchase orders retain independent snapshots.';
