-- LEGACY: retired by supabase-procurement-product-variants.sql.
-- Do not run this file on procurement v2; the supplier catalog tables no longer exist.
-- ECLADO procurement catalog and supplier price history.
-- Run after products, product_variants, admin_users, is_eclado_admin(),
-- and set_updated_at() exist.

create extension if not exists btree_gist with schema extensions;

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  default_currency text not null default 'USD',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint suppliers_code_not_blank check (btrim(code) <> ''),
  constraint suppliers_name_not_blank check (btrim(name) <> ''),
  constraint suppliers_default_currency_iso check (
    default_currency = upper(default_currency)
    and default_currency ~ '^[A-Z]{3}$'
  )
);

create unique index if not exists suppliers_code_unique
  on public.suppliers (lower(code));

create table if not exists public.supplier_items (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  supplier_sku text not null,
  name_en text not null,
  name_zh text,
  specification text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint supplier_items_sku_not_blank check (btrim(supplier_sku) <> ''),
  constraint supplier_items_name_en_not_blank check (btrim(name_en) <> '')
);

create unique index if not exists supplier_items_supplier_sku_unique
  on public.supplier_items (supplier_id, lower(supplier_sku));

create index if not exists supplier_items_supplier_active_idx
  on public.supplier_items (supplier_id, active, supplier_sku);

create table if not exists public.supplier_item_variant_links (
  supplier_item_id bigint not null references public.supplier_items(id) on delete cascade,
  product_variant_id bigint not null references public.product_variants(id) on delete cascade,
  conversion_quantity numeric(14, 4) not null default 1,
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (supplier_item_id, product_variant_id),
  constraint supplier_item_links_conversion_positive check (conversion_quantity > 0)
);

-- A storefront variant may have alternative supplier items, but only one primary
-- supplier item. An unlinked supplier item remains fully usable for procurement.
create unique index if not exists supplier_item_variant_primary_unique
  on public.supplier_item_variant_links (product_variant_id)
  where is_primary is true;

create index if not exists supplier_item_variant_links_variant_idx
  on public.supplier_item_variant_links (product_variant_id, supplier_item_id);

create table if not exists public.supplier_item_prices (
  id bigint generated by default as identity primary key,
  supplier_item_id bigint not null references public.supplier_items(id) on delete restrict,
  currency text not null default 'USD',
  unit_cost numeric(14, 4) not null,
  effective_from timestamptz not null default now(),
  effective_to timestamptz,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint supplier_item_prices_currency_iso check (
    currency = upper(currency)
    and currency ~ '^[A-Z]{3}$'
  ),
  constraint supplier_item_prices_cost_nonnegative check (unit_cost >= 0),
  constraint supplier_item_prices_valid_range check (
    effective_to is null or effective_to > effective_from
  )
);

-- Each supplier item has at most one open-ended price version.
create unique index if not exists supplier_item_prices_open_ended_unique
  on public.supplier_item_prices (supplier_item_id)
  where effective_to is null;

create index if not exists supplier_item_prices_history_idx
  on public.supplier_item_prices (supplier_item_id, effective_from desc);

-- Also prevent overlaps among closed historical ranges.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.supplier_item_prices'::regclass
      and conname = 'supplier_item_prices_no_overlap'
  ) then
    alter table public.supplier_item_prices
      add constraint supplier_item_prices_no_overlap
      exclude using gist (
        supplier_item_id with =,
        tstzrange(
          effective_from,
          coalesce(effective_to, 'infinity'::timestamptz),
          '[)'
        ) with &&
      );
  end if;
end;
$$;

drop trigger if exists trg_suppliers_updated_at on public.suppliers;
create trigger trg_suppliers_updated_at
  before update on public.suppliers
  for each row execute function public.set_updated_at();

drop trigger if exists trg_supplier_items_updated_at on public.supplier_items;
create trigger trg_supplier_items_updated_at
  before update on public.supplier_items
  for each row execute function public.set_updated_at();

drop trigger if exists trg_supplier_item_variant_links_updated_at
  on public.supplier_item_variant_links;
create trigger trg_supplier_item_variant_links_updated_at
  before update on public.supplier_item_variant_links
  for each row execute function public.set_updated_at();

alter table public.suppliers enable row level security;
alter table public.supplier_items enable row level security;
alter table public.supplier_item_variant_links enable row level security;
alter table public.supplier_item_prices enable row level security;

revoke all on table public.suppliers from anon, authenticated;
revoke all on table public.supplier_items from anon, authenticated;
revoke all on table public.supplier_item_variant_links from anon, authenticated;
revoke all on table public.supplier_item_prices from anon, authenticated;

grant select, insert, update, delete on table public.suppliers to authenticated;
grant select, insert, update, delete on table public.supplier_items to authenticated;
grant select, insert, update, delete on table public.supplier_item_variant_links to authenticated;
grant select on table public.supplier_item_prices to authenticated;

drop policy if exists "suppliers_admin_all" on public.suppliers;
create policy "suppliers_admin_all"
  on public.suppliers for all to authenticated
  using (public.is_eclado_admin())
  with check (public.is_eclado_admin());

drop policy if exists "supplier_items_admin_all" on public.supplier_items;
create policy "supplier_items_admin_all"
  on public.supplier_items for all to authenticated
  using (public.is_eclado_admin())
  with check (public.is_eclado_admin());

drop policy if exists "supplier_item_variant_links_admin_all"
  on public.supplier_item_variant_links;
create policy "supplier_item_variant_links_admin_all"
  on public.supplier_item_variant_links for all to authenticated
  using (public.is_eclado_admin())
  with check (public.is_eclado_admin());

drop policy if exists "supplier_item_prices_admin_select"
  on public.supplier_item_prices;
create policy "supplier_item_prices_admin_select"
  on public.supplier_item_prices for select to authenticated
  using (public.is_eclado_admin());

-- Price changes are append-only. This function closes the previous open-ended
-- version and inserts the next version atomically. The previous row is returned
-- unchanged when the submitted currency and cost already match.
create or replace function public.set_supplier_item_price(
  p_supplier_item_id bigint,
  p_unit_cost numeric,
  p_currency text default 'USD',
  p_effective_from timestamptz default now(),
  p_note text default null
)
returns public.supplier_item_prices
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_currency text := upper(btrim(coalesce(p_currency, '')));
  previous_price public.supplier_item_prices%rowtype;
  inserted_price public.supplier_item_prices%rowtype;
begin
  if not public.is_eclado_admin() and coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Administrator access required';
  end if;

  if p_unit_cost is null or p_unit_cost < 0 then
    raise exception 'Unit cost must be zero or greater';
  end if;

  if normalized_currency !~ '^[A-Z]{3}$' then
    raise exception 'Currency must be a three-letter ISO code';
  end if;

  if p_effective_from is null then
    raise exception 'Effective time is required';
  end if;

  -- Lock the parent row so concurrent price changes for one item serialize.
  perform 1
  from public.supplier_items
  where id = p_supplier_item_id
  for update;

  if not found then
    raise exception 'Supplier item % does not exist', p_supplier_item_id;
  end if;

  select *
  into previous_price
  from public.supplier_item_prices
  where supplier_item_id = p_supplier_item_id
    and effective_to is null
  order by effective_from desc, id desc
  limit 1
  for update;

  if found then
    if previous_price.currency = normalized_currency
       and previous_price.unit_cost = p_unit_cost then
      return previous_price;
    end if;

    if p_effective_from <= previous_price.effective_from then
      raise exception 'New effective time must be later than the current price start time';
    end if;

    update public.supplier_item_prices
    set effective_to = p_effective_from
    where id = previous_price.id;
  end if;

  insert into public.supplier_item_prices (
    supplier_item_id,
    currency,
    unit_cost,
    effective_from,
    note,
    created_by
  ) values (
    p_supplier_item_id,
    normalized_currency,
    p_unit_cost,
    p_effective_from,
    nullif(btrim(coalesce(p_note, '')), ''),
    auth.uid()
  )
  returning * into inserted_price;

  return inserted_price;
end;
$$;

revoke all on function public.set_supplier_item_price(bigint, numeric, text, timestamptz, text)
  from public, anon;
grant execute on function public.set_supplier_item_price(bigint, numeric, text, timestamptz, text)
  to authenticated, service_role;

comment on table public.suppliers is
  'Suppliers available to procurement. Storefront products remain independent.';
comment on table public.supplier_items is
  'Supplier-owned procurement catalog keyed by supplier SKU; items may exist without a storefront product.';
comment on table public.supplier_item_variant_links is
  'Optional mapping from supplier procurement items to storefront product variants.';
comment on table public.supplier_item_prices is
  'Non-overlapping effective-dated supplier unit cost history.';
comment on function public.set_supplier_item_price(bigint, numeric, text, timestamptz, text) is
  'Atomically closes the previous supplier price and appends a new effective-dated price version.';

insert into public.suppliers (code, name, default_currency, active)
values ('ECLADO_KR', 'ECLADO Korea', 'USD', true)
on conflict (lower(code)) do update
set
  name = excluded.name,
  default_currency = excluded.default_currency,
  active = true;
