// Optional isolated PostgreSQL/WASM integration test. No Supabase credentials.
// PGLITE_MODULE=/absolute/path/to/@electric-sql/pglite/dist/index.js node --test tests/integration/member-pricing-db.test.cjs
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '../..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
function functionDefinition(file, name) {
  const source = read(file);
  const start = source.indexOf(`create or replace function public.${name}(`);
  assert(start >= 0, `Missing source function ${name}`);
  const end = source.indexOf('$$;', source.indexOf('as $$', start));
  return source.slice(start, end + 3);
}

test('isolated DB: migration, authoritative prices, saves, roles, audit, stale versions and rerun', { skip:!process.env.PGLITE_MODULE }, async () => {
  const { PGlite } = await import(pathToFileURL(process.env.PGLITE_MODULE).href);
  const db = new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated;
      create schema auth;
      create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.user_id',true),'')::uuid $$;
      create function auth.role() returns text language sql as $$ select 'authenticated'::text $$;
      create function auth.jwt() returns jsonb language sql as $$ select '{"email":"admin@test.invalid","role":"authenticated"}'::jsonb $$;
      create function public.has_backoffice_permission(p text) returns boolean language sql as $$ select current_setting('test.access',true)='admin' or (current_setting('test.access',true)='editor' and p in ('catalog.read','catalog.write')) $$;
      create function public.is_eclado_backoffice_user() returns boolean language sql as $$ select current_setting('test.access',true) in ('admin','editor') $$;
      create table public.admin_users(user_id uuid, role text, active boolean);
      create table public.backoffice_role_permissions(role text, permission text, primary key(role,permission),
        constraint backoffice_role_permissions_permission_check check (permission in (
          'catalog.read','catalog.write','orders.read','orders.write','members.read','members.write',
          'promotions.manage','procurement.manage','analytics.read','audit_logs.read','notifications.send',
          'backorders.manage','inventory_counts.manage','shopping_credit.manage','future_existing.manage')));
      create table public.membership_tiers(role text primary key, professional_price_multiplier numeric, active boolean default true, can_buy_pro_products boolean default true);
      create table public.profiles(id uuid, role text);
      create table public.products(
        id integer generated by default as identity primary key, asset_key uuid, name text, name_zh text, subtitle text, category text, series text,
        min_stock integer, is_pro_only boolean default false, apply_tier_multiplier boolean default true, image_url text, image_urls jsonb,
        description text, skin_type text, ingredients text, features jsonb, source_folder_name text, imported_from_drive boolean,
        product_list_image_scale numeric, publication_status text default 'active', active boolean default true,
        size text, price numeric, pro_price numeric, stock integer, variants jsonb, updated_at timestamptz
      );
      create table public.product_variants(
        id bigint generated by default as identity primary key, product_id integer, sku text, size text, price numeric, pro_price numeric,
        stock integer, is_default boolean, sort_order integer, active boolean, is_custom_order boolean default false,
        procurement_unit_cost_usd numeric, gift_enabled boolean default false, gift_stock integer default 0, gift_min_stock integer default 3, updated_at timestamptz
      );
      create table public.product_images(id bigint,product_id integer, storage_path text,alt_text text,active boolean,is_primary boolean,sort_order integer);
      create table public.promotions(id uuid,name text,discount_rate numeric,discount_amount numeric,discount_order text,product_ids integer[],created_at timestamptz,active boolean,benefit_type text,activation_type text,archived_at timestamptz,start_at timestamptz,end_at timestamptz);
      create table public.audit_logs(id bigint generated always as identity, actor_user_id uuid,actor_email text,actor_role text,actor_type text,action text,entity_type text,entity_id text,before_data jsonb,after_data jsonb,metadata jsonb);
      create table public.orders(id text, total numeric,items jsonb);
      insert into public.orders values ('old-order',7000,'[{"unit_price":700,"qty":10}]');
      create function public.calculate_order_shipping(items jsonb) returns numeric language sql as $$ select 120::numeric $$;
      create function public.get_storefront_catalog() returns jsonb language sql as $$ select jsonb_build_object('products',coalesce((select jsonb_agg(to_jsonb(p)) from public.products p),'[]'::jsonb),'variants','[]'::jsonb,'images','[]'::jsonb) $$;
      create function public.get_event_catalog() returns jsonb language sql as $$ select public.get_storefront_catalog() $$;
      create function public.get_admin_catalog() returns jsonb language plpgsql as $$ begin if not public.has_backoffice_permission('catalog.read') then raise exception 'denied' using errcode='42501'; end if; return public.get_storefront_catalog(); end $$;
      insert into public.membership_tiers values ('consumer',null,true,false),('pro',1,true,true),('instructor',0.7,true,true),('distributor',0.65,true,true),('staff',0.5,true,true);
      alter table public.membership_tiers add column updated_at timestamptz;
      insert into public.products(asset_key,name,name_zh,category,price,pro_price,stock,apply_tier_multiplier) values
        (gen_random_uuid(),'Normal','一般商品','其他',2000,1000,20,true),
        (gen_random_uuid(),'Fixed','固定專業價','其他',2000,1000,20,false);
      insert into public.product_variants(product_id,sku,size,price,pro_price,stock,is_default,sort_order,active) values (1,'A','100ml',2000,1000,20,true,0,true),(1,'B','200ml',4000,2000,20,false,1,true),(2,'C','100ml',2000,1000,20,true,0,true);
      select set_config('test.user_id','11111111-1111-4111-8111-111111111111',false);
      select set_config('test.access','admin',false);
      insert into public.profiles values ('11111111-1111-4111-8111-111111111111','instructor');
      insert into public.admin_users values ('11111111-1111-4111-8111-111111111111','admin',true);
    `);
    await db.exec(functionDefinition('supabase-promotion-pricing-engine.sql','quote_order_pricing').replace('public.quote_order_pricing(', 'public.quote_order_pricing_internal_20260916('));
    await db.exec(functionDefinition('supabase-save-product-with-variants.sql','save_product_with_variants'));
    // Reproduce a deployed projection with different formatting and extra fields.
    const installedProjection = functionDefinition('supabase-system-audit-logs.sql','audit_log_projection')
      .replace("'apply_tier_multiplier', row_data -> 'apply_tier_multiplier',", "'site_specific_field', row_data->'site_specific_field',\n      'apply_tier_multiplier',row_data->'apply_tier_multiplier',");
    await db.exec(installedProjection);
    await db.exec(functionDefinition('supabase-system-audit-logs.sql','capture_admin_audit_log'));
    await db.exec(functionDefinition('supabase-internal-staff-member.sql','get_storefront_catalog'));
    await db.exec(functionDefinition('supabase-internal-staff-member.sql','get_event_catalog'));
    await db.exec(functionDefinition('supabase-backoffice-permissions.sql','get_admin_catalog'));
    await db.exec("create trigger products_audit after update on public.products for each row execute function public.capture_admin_audit_log('id')");
    const migration = read('supabase-member-pricing.sql');
    await db.exec(migration);
    const preservedAudit = await db.query(`select public.audit_log_projection('products','{"id":1,"site_specific_field":"preserved","instructor_price_multiplier":0.88}'::jsonb) as data`);
    assert.equal(preservedAudit.rows[0].data.site_specific_field,'preserved');
    assert.equal(preservedAudit.rows[0].data.instructor_price_multiplier,0.88);
    assert.equal(preservedAudit.rows[0].data.staff_price_multiplier,null);
    const pricingPermissions = await db.query("select role from public.backoffice_role_permissions where permission='member_pricing.manage' order by role");
    assert.deepEqual(pricingPermissions.rows.map(row => row.role), ['admin','super_admin']);
    await db.exec("insert into public.backoffice_role_permissions values ('admin','future_existing.manage')");
    await assert.rejects(db.exec("insert into public.backoffice_role_permissions values ('admin','unknown.manage')"), /permission_check/);
    const query = async (sql, params=[]) => (await db.query(sql,params)).rows;
    const one = async (sql, params=[]) => (await query(sql,params))[0];
    const quote = async (id=1,variant=null,qty=10) => (await one('select public.quote_order_pricing_internal_20260916($1::jsonb) as result',[JSON.stringify([{product_id:id,variant_id:variant,qty}])])).result;
    assert.equal((await quote()).items[0].unit_price,700);
    assert.equal((await quote(2)).items[0].unit_price,1000);
    assert.deepEqual((await one('select instructor_price_multiplier,distributor_price_multiplier,staff_price_multiplier from public.products where id=2')), {instructor_price_multiplier:'1',distributor_price_multiplier:'1',staff_price_multiplier:'1'});
    const snapshot = (await one('select public.get_admin_member_pricing() as result')).result.multipliers;
    assert.deepEqual(snapshot,{instructor:0.7,distributor:0.65,staff:0.5});
    const globalSave = (values,expected=snapshot) => db.query('select public.save_member_pricing($1::jsonb,$2::jsonb)',[JSON.stringify(values),JSON.stringify(expected)]);
    await globalSave({...snapshot,instructor:0.8,staff:0.4});
    assert.equal((await quote()).items[0].unit_price,800);
    await assert.rejects(db.query('select public.quote_order_pricing_internal_20260916($1::jsonb)', [JSON.stringify([{product_id:1,qty:10,expected_unit_price:700}])]), /商品價格已更新/);
    assert.equal((await one('select public.quote_order_pricing_internal_20260916($1::jsonb) as result',[JSON.stringify([{product_id:1,qty:10,expected_unit_price:800}])])).result.items[0].unit_price,800);
    await assert.rejects(globalSave(snapshot), /Pricing settings changed/);
    await assert.rejects(globalSave({...snapshot,instructor:0}), /Fold must/);
    await assert.rejects(globalSave({...snapshot,instructor:1.1}), /Fold must/);
    await assert.rejects(globalSave({...snapshot,instructor:0.8888}), /Fold must/);
    await db.exec("select set_config('test.access','editor',false)");
    await assert.rejects(globalSave(snapshot), /manage access required/);
    await db.exec("select set_config('test.access','admin',false)");
    const product = {id:1,name:'Normal',name_zh:'一般商品',category:'其他',instructor_price_multiplier:0.88,distributor_price_multiplier:null,staff_price_multiplier:1,expected_pricing_overrides:{instructor:null,distributor:null,staff:null}};
    const variants = [{id:'1',sku:'A',size:'100ml',price:2000,pro_price:1000,stock:20,is_default:true,sort_order:0,active:true},{id:'2',sku:'B',size:'200ml',price:4000,pro_price:2000,stock:20,is_default:false,sort_order:1,active:true}];
    const productSave = value => db.query('select public.save_product_with_variants($1::jsonb,$2::jsonb)',[JSON.stringify(value),JSON.stringify(variants)]);
    await productSave(product);
    assert.equal((await quote()).items[0].unit_price,880);
    assert.equal((await quote(1,'2')).items[0].unit_price,1760);
    await assert.rejects(productSave(product), /Product pricing changed/);
    const withoutSnapshot = { ...product }; delete withoutSnapshot.expected_pricing_overrides;
    await assert.rejects(productSave(withoutSnapshot), /Original product pricing snapshot required/);
    await assert.rejects(productSave({ ...product,expected_pricing_overrides:{instructor:0.88,distributor:null,staff:1},staff_price_multiplier:1.1 }), /staff_price_multiplier_check/);
    await db.exec("update public.profiles set role='distributor'");
    assert.equal((await quote()).items[0].unit_price,650);
    await db.exec("update public.profiles set role='staff'");
    assert.equal((await quote(1,null,1)).items[0].unit_price,1000);
    assert.equal((await quote(1,null,1)).shipping,0);
    await db.exec("update public.profiles set role='consumer'");
    assert.equal((await quote()).items[0].unit_price,2000);
    const catalog = (await one('select public.get_storefront_catalog() as result')).result;
    assert.equal(catalog.member_pricing_version,1);
    assert.equal(catalog.products[0].pro_price,null);
    assert.equal(catalog.variants[0].pro_price,null);
    assert.ok(!Object.hasOwn(catalog.variants[0],'procurement_unit_cost_usd'));
    assert.ok(!Object.hasOwn(catalog.variants[0],'gift_stock'));
    assert.equal(catalog.products[0].pricing_defaults.instructor,0.8);
    await db.exec("update public.profiles set role='pro'");
    assert.equal((await quote()).items[0].unit_price,1000);
    await db.exec("update public.product_variants set pro_price=0 where product_id=2; update public.profiles set role='staff'");
    assert.equal((await quote(2,null,1)).items[0].unit_price,0); // Preserve legacy fixed professional price, including zero.
    await db.exec("select set_config('test.access','none',false)");
    await assert.rejects(productSave(product), /Catalog write authorization/);
    await db.exec("select set_config('test.access','admin',false)");
    const globalAudit = await query("select before_data,after_data from public.audit_logs where entity_type='membership_tiers'");
    assert.equal(globalAudit.length,2);
    assert.ok(globalAudit.some(row => row.before_data.professional_price_multiplier===0.7 && row.after_data.professional_price_multiplier===0.8));
    assert.ok((await query("select after_data from public.audit_logs where entity_type='products'")).some(row => row.after_data.instructor_price_multiplier===0.88));
    await db.exec(migration); // Must not reset custom/global prices or rerun legacy conversion.
    await db.exec(read('supabase-member-pricing-verify.sql'));
    assert.equal((await one('select instructor_price_multiplier from public.products where id=1')).instructor_price_multiplier,'0.88');
    assert.equal((await one("select professional_price_multiplier from public.membership_tiers where role='instructor'")).professional_price_multiplier,'0.8');
    assert.equal((await one("select total from public.orders where id='old-order'")).total,'7000');
    assert.equal((await one("select has_function_privilege('anon','public.resolve_product_price_multiplier(public.products,text,numeric)','execute') as allowed")).allowed,false);
    assert.equal((await one("select has_function_privilege('authenticated','public.quote_order_pricing_internal_20260916(jsonb,text)','execute') as allowed")).allowed,false);
    console.log('PASS: actual SQL migration and rerun, quote prices across identities/variants, atomic product save, stale versions, audit, historical preservation and helper ACLs');
  } finally { await db.close(); }
});
